# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Faker-JapaneseFemaleName
version:      0.02
version_from: lib/Data/Faker/JapaneseFemaleName.pm
installdirs:  site
requires:
    Data::Faker:                   0
    Pod::Parser:                   1.35
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
